const ACCEPTANCE_PAY_PER_ROW = 7.2;
const PLACEMENT_PAY_PER_ROW = 7.1;
const ACCEPTANCE_PAY_PER_QUANTITY = 0.6;
const PLACEMENT_PAY_PER_QUANTITY = ACCEPTANCE_PAY_PER_QUANTITY;

const SPLIT_RATE = 0.3; //Доля, которая уходит в общак

const MAX_VALUE = 100000000; // Максимальное значение для строк и количества

export {
  ACCEPTANCE_PAY_PER_QUANTITY,
  ACCEPTANCE_PAY_PER_ROW,
  MAX_VALUE,
  PLACEMENT_PAY_PER_QUANTITY,
  PLACEMENT_PAY_PER_ROW,
  SPLIT_RATE,
};
